<a href="https://colab.research.google.com/github/flash1zx/Machine-learningE/blob/main/ProjectSales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
import os
os.listdir("/content")

['.config',
 'Sales_July_2019.csv',
 'Sales_February_2019.csv',
 '.ipynb_checkpoints',
 'Sales_December_2019.csv',
 'Sales_November_2019.csv',
 'Sales_June_2019.csv',
 'Sales_May_2019.csv',
 'Sales_August_2019.csv',
 'Sales_September_2019.csv',
 'Sales_January_2019.csv',
 'Sales_October_2019.csv',
 'Sales_March_2019.csv',
 'Sales_April_2019.csv',
 'sample_data']

In [ ]:
import os
for x in os.listdir("/content"):
  if "Sales" in x:
    print(x)

Sales_July_2019.csv
Sales_February_2019.csv
Sales_December_2019.csv
Sales_November_2019.csv
Sales_June_2019.csv
Sales_May_2019.csv
Sales_August_2019.csv
Sales_September_2019.csv
Sales_January_2019.csv
Sales_October_2019.csv
Sales_March_2019.csv
Sales_April_2019.csv

In [ ]:
dataset = pd.DataFrame()
for x in os.listdir("/content"):
  if "Sales" in x:
    d = pd.read_csv(f"/content/{x}")
    dataset = pd.concat([dataset, d])

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 186850 entries, 0 to 18382
Data columns (total 6 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Order ID          186305 non-null  object
 1   Product           186305 non-null  object
 2   Quantity Ordered  186305 non-null  object
 3   Price Each        186305 non-null  object
 4   Order Date        186305 non-null  object
 5   Purchase Address  186305 non-null  object
dtypes: object(6)
memory usage: 10.0+ MB

In [ ]:
dataset.shape[0]

186850

In [ ]:
dataset.isnull().sum()/dataset.shape[0]*100

Order ID            0.291678
Product             0.291678
Quantity Ordered    0.291678
Price Each          0.291678
Order Date          0.291678
Purchase Address    0.291678
dtype: float64

In [ ]:
dataset.shape

(186850, 6)

In [ ]:
dataset.dropna(axis=0, inplace=True)

Removing null values

In [ ]:
dataset

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,222910,Apple Airpods Headphones,1,150,07/26/19 16:51,"389 South St, Atlanta, GA 30301"
1,222911,Flatscreen TV,1,300,07/05/19 08:55,"590 4th St, Seattle, WA 98101"
2,222912,AA Batteries (4-pack),1,3.84,07/29/19 12:41,"861 Hill St, Atlanta, GA 30301"
3,222913,AA Batteries (4-pack),1,3.84,07/28/19 10:15,"190 Ridge St, Atlanta, GA 30301"
4,222914,AAA Batteries (4-pack),5,2.99,07/31/19 02:13,"824 Forest St, Seattle, WA 98101"
...,...,...,...,...,...,...
18378,194090,Google Phone,1,600,04/08/19 17:11,"177 Jackson St, Los Angeles, CA 90001"
18379,194091,AA Batteries (4-pack),1,3.84,04/15/19 16:02,"311 Forest St, Austin, TX 73301"
18380,194092,AAA Batteries (4-pack),2,2.99,04/28/19 14:36,"347 Sunset St, San Francisco, CA 94016"
18381,194093,AA Batteries (4-pack),1,3.84,04/14/19 15:09,"835 Lake St, Portland, OR 97035"
18382,194094,Lightning Charging Cable,1,14.95,04/18/19 11:08,"354 North St, Boston, MA 02215"

In [ ]:
dataset.to_csv('/content/Output.csv', index=False)

In [ ]:
dataset = pd.read_csv("Output.csv")

Question:1
Which month has the highest amount of sales in the dataset??

In [19]:
dataset.head()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,222910,Apple Airpods Headphones,1,150,07/26/19 16:51,"389 South St, Atlanta, GA 30301"
1,222911,Flatscreen TV,1,300,07/05/19 08:55,"590 4th St, Seattle, WA 98101"
2,222912,AA Batteries (4-pack),1,3.84,07/29/19 12:41,"861 Hill St, Atlanta, GA 30301"
3,222913,AA Batteries (4-pack),1,3.84,07/28/19 10:15,"190 Ridge St, Atlanta, GA 30301"
4,222914,AAA Batteries (4-pack),5,2.99,07/31/19 02:13,"824 Forest St, Seattle, WA 98101"

In [20]:
dataset.Product.value_counts()

Product
USB-C Charging Cable          21903
Lightning Charging Cable      21658
AAA Batteries (4-pack)        20641
AA Batteries (4-pack)         20577
Wired Headphones              18882
Apple Airpods Headphones      15549
Bose SoundSport Headphones    13325
27in FHD Monitor               7507
iPhone                         6842
27in 4K Gaming Monitor         6230
34in Ultrawide Monitor         6181
Google Phone                   5525
Flatscreen TV                  4800
Macbook Pro Laptop             4724
ThinkPad Laptop                4128
20in Monitor                   4101
Vareebadd Phone                2065
LG Washing Machine              666
LG Dryer                        646
Product                         355
Name: count, dtype: int64

Removing Product Column

In [21]:
dataset = dataset[dataset["Product"] != "Product"]

In [23]:
dataset.shape

(185950, 6)

In [25]:
dataset.dtypes

Order ID            object
Product             object
Quantity Ordered    object
Price Each          object
Order Date          object
Purchase Address    object
dtype: object

In [47]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 185950 entries, 0 to 186304
Data columns (total 8 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Order ID          185950 non-null  object
 1   Product           185950 non-null  object
 2   Quantity Ordered  185950 non-null  int64
 3   Price Each        185950 non-null  float64
 4   Order Date        185950 non-null  object
 5   Purchase Address  185950 non-null  object
 6   Sales             185950 non-null  float64
 7   Month             185950 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 12.8+ MB

In [26]:
dataset.head()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,222910,Apple Airpods Headphones,1,150,07/26/19 16:51,"389 South St, Atlanta, GA 30301"
1,222911,Flatscreen TV,1,300,07/05/19 08:55,"590 4th St, Seattle, WA 98101"
2,222912,AA Batteries (4-pack),1,3.84,07/29/19 12:41,"861 Hill St, Atlanta, GA 30301"
3,222913,AA Batteries (4-pack),1,3.84,07/28/19 10:15,"190 Ridge St, Atlanta, GA 30301"
4,222914,AAA Batteries (4-pack),5,2.99,07/31/19 02:13,"824 Forest St, Seattle, WA 98101"

In [27]:
dataset["Quantity Ordered"] = pd.to_numeric(dataset["Quantity Ordered"])

In [28]:
dataset["Price Each"] = pd.to_numeric(dataset["Price Each"])

In [30]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 185950 entries, 0 to 186304
Data columns (total 6 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Order ID          185950 non-null  object
 1   Product           185950 non-null  object
 2   Quantity Ordered  185950 non-null  int64
 3   Price Each        185950 non-null  float64
 4   Order Date        185950 non-null  object
 5   Purchase Address  185950 non-null  object
dtypes: float64(1), int64(1), object(4)
memory usage: 9.9+ MB

In [31]:
dataset["Sales"] = dataset["Price Each"] * dataset["Quantity Ordered"]

In [32]:
dataset.head

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Sales
0,222910,Apple Airpods Headphones,1,150.00,07/26/19 16:51,"389 South St, Atlanta, GA 30301",150.00
1,222911,Flatscreen TV,1,300.00,07/05/19 08:55,"590 4th St, Seattle, WA 98101",300.00
2,222912,AA Batteries (4-pack),1,3.84,07/29/19 12:41,"861 Hill St, Atlanta, GA 30301",3.84
3,222913,AA Batteries (4-pack),1,3.84,07/28/19 10:15,"190 Ridge St, Atlanta, GA 30301",3.84
4,222914,AAA Batteries (4-pack),5,2.99,07/31/19 02:13,"824 Forest St, Seattle, WA 98101",14.95

In [37]:
dataset["Order Date"].str[:2]

0         07
1         07
2         07
3         07
4         07
          ..
186300    04
186301    04
186302    04
186303    04
186304    04
Name: Order Date, Length: 185950, dtype: object

In [35]:
dataset["Month"] = dataset["Order Date"].str[:2]

In [44]:
dataset.head()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Sales,Month
0,222910,Apple Airpods Headphones,1,150.00,07/26/19 16:51,"389 South St, Atlanta, GA 30301",150.00,07
1,222911,Flatscreen TV,1,300.00,07/05/19 08:55,"590 4th St, Seattle, WA 98101",300.00,07
2,222912,AA Batteries (4-pack),1,3.84,07/29/19 12:41,"861 Hill St, Atlanta, GA 30301",3.84,07
3,222913,AA Batteries (4-pack),1,3.84,07/28/19 10:15,"190 Ridge St, Atlanta, GA 30301",3.84,07
4,222914,AAA Batteries (4-pack),5,2.99,07/31/19 02:13,"824 Forest St, Seattle, WA 98101",14.95,07

In [45]:
dataset.Month.value_counts()

Month
12    24984
10    20282
04    18279
11    17573
05    16566
03    15153
07    14293
06    13554
02    11975
08    11961
09    11621
01     9709
Name: count, dtype: int64

In [46]:
dataset.groupby("Month")["Sales"].sum().sort_values(ascending=False)

Month
12    4613443.34
10    3736726.88
04    3390670.24
11    3199603.20
05    3152606.75
03    2807100.38
07    2647775.76
06    2577802.26
08    2244467.88
02    2202022.42
09    2097560.13
01    1822256.73
Name: Sales, dtype: float64

Answer to question 1:
Therfore, 12th month which is december is the month with the highest amount of Sales

Question:2
Which city sold most product?

In [48]:
dataset.head()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Sales,Month
0,222910,Apple Airpods Headphones,1,150.00,07/26/19 16:51,"389 South St, Atlanta, GA 30301",150.00,07
1,222911,Flatscreen TV,1,300.00,07/05/19 08:55,"590 4th St, Seattle, WA 98101",300.00,07
2,222912,AA Batteries (4-pack),1,3.84,07/29/19 12:41,"861 Hill St, Atlanta, GA 30301",3.84,07
3,222913,AA Batteries (4-pack),1,3.84,07/28/19 10:15,"190 Ridge St, Atlanta, GA 30301",3.84,07
4,222914,AAA Batteries (4-pack),5,2.99,07/31/19 02:13,"824 Forest St, Seattle, WA 98101",14.95,07

In [49]:
dataset["Purchase Address"].str.split(",").str[1]

0                Atlanta
1                Seattle
2                Atlanta
3                Atlanta
4                Seattle
               ...
186300       Los Angeles
186301            Austin
186302     San Francisco
186303          Portland
186304            Boston
Name: Purchase Address, Length: 185950, dtype: object

In [50]:
dataset["City"] = dataset["Purchase Address"].str.split(",").str[1]

adding city column

In [53]:
dataset.head()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Sales,Month,City
0,222910,Apple Airpods Headphones,1,150.00,07/26/19 16:51,"389 South St, Atlanta, GA 30301",150.00,07,Atlanta
1,222911,Flatscreen TV,1,300.00,07/05/19 08:55,"590 4th St, Seattle, WA 98101",300.00,07,Seattle
2,222912,AA Batteries (4-pack),1,3.84,07/29/19 12:41,"861 Hill St, Atlanta, GA 30301",3.84,07,Atlanta
3,222913,AA Batteries (4-pack),1,3.84,07/28/19 10:15,"190 Ridge St, Atlanta, GA 30301",3.84,07,Atlanta
4,222914,AAA Batteries (4-pack),5,2.99,07/31/19 02:13,"824 Forest St, Seattle, WA 98101",14.95,07,Seattle

In [61]:
dataset.City.unique()

array([' Atlanta', ' Seattle', ' San Francisco', ' New York City',
       ' Los Angeles', ' Dallas', ' Boston', ' Portland', ' Austin'],
      dtype=object)

In [62]:
dataset.groupby("City")["Sales"].sum().sort_values(ascending=False)

City
 San Francisco    8262203.91
 Los Angeles      5452570.80
 New York City    4664317.43
 Boston           3661642.01
 Atlanta          2795498.58
 Dallas           2767975.40
 Seattle          2747755.48
 Portland         2320490.61
 Austin           1819581.75
Name: Sales, dtype: float64

Answer to question 2:
Therefore, SanFranciso has the most amount of sales